# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 北京邮电大学开源软件镜像站
# title: 北京外国语大学开源软件镜像站
school: 北京邮电大学
# school: 北京外国语大学
brand: BUPT Mirror
operator: 北京邮电大学信息化技术中心
# operator: 北外信息技术中心
logo: false
meow_404: true
issue_tag: tuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
urlauto: "https://mirrors.bupt.edu.cn"
hostname: "mirrors.bupt.edu.cn"
#urlv4: "https://mirrors4.tuna.tsinghua.edu.cn"
#urlv6: "https://mirrors6.tuna.tsinghua.edu.cn"
#aosp: "aosp.tuna.tsinghua.edu.cn"
#arch_archive: "arch-archive.tuna.tsinghua.edu.cn"
#aur: "aur.tuna.tsinghua.edu.cn"
#pypi: "pypi.tuna.tsinghua.edu.cn"
homelink: "https://nic.bupt.edu.cn"
hide_navbar: true
hide_download: true
hide_server_status: true

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel
    - jekyll-sitemap

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]

# vim: ts=2 sts=2 sw=2 expandtab
